### ISSUE TITLE
DOPA Expansion

### ISSUE THREAD

**Issue by ewewo2** [tomkidd/Quake-iOS#3]
Only 3 Expansion showing up in menu, DOPA is not selectavble

**Comment by tomkidd** [comment]
DOPA is considered a "fifth episode" to the original game (E5M1, etc.) so to get to it you choose the original game, then "Select Episode" and then pick the fifth episode. 

I think I have code in there to only show it if you have the files included to avoid a crash but it's not shown as a separate expansion.
